name: stories_page_view
description: A Flutter package for creating a instagram like story. 
version: 0.0.2-alpha.1
homepage: https://github.com/Blocship/stories_page_view

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
